### ISSUE TITLE
在github中撒娇

### ISSUE THREAD

**Issue by alissli** [alissli/-Github-#8]
@zoeyzoey0102
@Zxlon

**Comment by zoeyzoey0102** [comment]
真爱！你们好哇！

@zoeyzoey0102 为什么我也可以编辑你的issue

**Comment by alissli** [comment]
这样子可以收到通知啦？

**Comment by zoeyzoey0102** [comment]
嘻嘻可以咯

**Comment by ghost** [comment]
- 权限是可以设置的吧
  - 我在 大妈 的怼圈私库。
  - 我在 Fork 别人的仓库时，竟然有选项是 Fork 到怼圈。
  - Github 我还需要花时间继续怼。
  - 接下来分享一篇最近的自怼日记给你们，反正这里人少。
  - [170419-S01E01.2 内心独白](https://github.com/Zxlon/zxlon.github.io/blob/master/_posts/du_s01e01_Zxlon_usage.md)

**Comment by alissli** [comment]
@Zxlon 我最初本来想是不是能邀请你们，但是好像没找到怎么做。github里协作项目是通过每个人fork仓库？

**Comment by ghost** [comment]
Fork 与 不 Fork 这是个问题，不过就我们目前这种来说，不需要 Fork 。

**Comment by ghost** [comment]
既然是真爱，你们也分享一点小秘密出来噻～
我把自己的内心独白都分享了。

**Comment by zoeyzoey0102** [comment]
此人最近恋爱中...以及申请签证准备去美国出差三个月，如果顺利的话。
所以通识的书单稍微搁置了一下，生活复杂度稍微增加了一点，正在重新平衡，重回正轨。
你们都Py和写得不亦虐呼啊！抗压力十级，佩服佩服！

**Comment by alissli** [comment]
楼上正向着新生活大步迈嘛，可喜可贺！
@Zxlon 的内心独白看了2遍才多少明白。

生活向左，工作向右，学习节奏当中过
我过着割裂的生活已许久许久，有时候真想全部都甩开
《转行》翻过了三章，印证了猜想：边做边想，还有什么好埋汰！

**Comment by ghost** [comment]
@alissli 
- 我写得挺烂的，没有修辞、没有技法、就连错别字也懒得改。
- 割裂这件事，你并不孤独，释怀些，遇事 > 分解 > 再分解 > 减少焦虑。
- 抛不抛开主要看环境/人/事儿，是不是时间的朋友。

@zoeyzoey0102 
- 怎么我第一印象就觉得你男友是老外呢？

**Comment by alissli** [comment]
@zoeyzoey0102 也有可能是个女孩子吗？

**Comment by zoeyzoey0102** [comment]
@Zxlon 哈哈还真不是
@alissli good guess! 男孩子女孩子我都喜欢，目前是男孩子...害羞脸

似乎我们仨最近在工作上都有小变动，实际的或者还未付诸实际的。想到你们俩生活复杂度更大，还能坚持精进学习，真是非常可贵的同辈鼓励！我们需要的就是深度思考，和最小行动！以及，给自己一点转变的时间和透气的空间呢。

**Comment by alissli** [comment]
@Zxlon @zoeyzoey0102 
开智姗姗的这篇博客分享给你们，我不害怕割裂，只是在“合一”的路上有些疲惫
[想让生活不再满是工作？试试远距联想](http://ishanshan.top/murmur/TipsWorkHappier.html)
>  好的模式是-学习就是工作，工作就是学习，工作和学习合一。低阶学习者把学习工作生活越割裂，越什么都得不到。
